return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  dependencies = {
    { "HiPhish/rainbow-delimiters.nvim", event = { "BufReadPre", "BufNewFile" } },
    { "RRethy/nvim-treesitter-endwise", event = { "BufReadPre", "BufNewFile" } },
    { "folke/ts-comments.nvim", event = { "BufReadPre", "BufNewFile" } },
    {
      "andymass/vim-matchup",
      event = { "BufReadPre", "BufNewFile" },
      init = function() vim.g.matchup_matchparen_offscreen = { method = "popup" } end,
    },
  },
  version = false,
  build = ":TSUpdate",
  opts = {
    highlight = { enable = true },
    indent = { enable = true, disable = { "python" } },
    endwise = { enable = true },
    autopairs = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "dockerfile",
      "json",
      "lua",
      "markdown",
      "python",
      "query",
      "regex",
      "toml",
      "vim",
      "yaml",
    },
  },
  config = true,
}
